# If you found my work useful and wish to give thanks or support my random obsessions, feel free to use the link below or to contribute to the project :)
# Buy Me A Coffee: https://buymeacoffee.com/stephanroos
buy_me_a_coffee: stephanroos

# Financial support is not required, but I always sincerely appreciate it.
# Many thanks are extended to all who support open-source projects.
